"""
Django settings for personal_website project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# la directory base è il punto di partenza per localhost di connettersi
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# chiave di accesso per l'amministrazione del server
SECRET_KEY = 'o48nvuuv5*3$z_l5nh_&uk-fjf4b@4l3c&wvq0vui#80s%(f&t'

# questa opzione consente a django di scrivere su una pagina eventuali errori
DEBUG = True

# host ai quali è consentito ospitare il sito
ALLOWED_HOSTS = ["localhost"]


# questa lista contiene i nomi delle app presenti nell'applicazione, comprese quelle create ad hoc
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portfolio',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'personal_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'personal_website.wsgi.application'

# questa lista contiene tutti i database che l'applicazione utilizza
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# questa lista contiene tutti i metodi di controllo per il login utilizzati dall'applicazione, sia per utenti normali che per amministratori del sito
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalizzazione

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# posizione della cartella static, dove vengono salvati i file comuni a tutto il progetto

STATIC_URL = '/static/'

#queste de variabili servono per consentire a django di salvare immagini all'interno del progetto
# media_url è il nome della directory, mentre media_root costruisce il path della directory
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')