# Generated by Django 3.0.5 on 2020-04-28 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/images')),
                ('url', models.URLField(blank=True)),
                ('text', models.TextField(default='')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 28, 16, 41, 48, 791270))),
            ],
        ),
    ]
